### ISSUE TITLE
Setting app cache on linux web app results in failure to start up container

### ISSUE THREAD

**Issue by damiand2** [Azure-App-Service/ImageBuilder#123]
steps to reproduce:
1. create linux webapp in azure (.net core 3.1 LTS)
2. set configuration blade:
[  
  {
    "name": "WEBSITE_RUN_FROM_PACKAGE",
    "value": "1",
    "slotSetting": false
  },
  {
    "name": "WEBSITES_ENABLE_APP_CACHE",
    "value": "true",
    "slotSetting": false
  }
]
3. deploy app (here using azure devops (logs from task):
Starting: Azure App Service Deploy: xxxxxxx
==============================================================================
Task         : Azure App Service deploy
Description  : Deploy to Azure App Service a web, mobile, or API app using Docker, Java, .NET, .NET Core, Node.js, PHP, Python, or Ruby
Version      : 4.184.4
Author       : Microsoft Corporation
Help         : https://aka.ms/azureappservicetroubleshooting
==============================================================================
Got service connection details for Azure App Service:'xxxxxxxxxxx'
Trying to update App Service Application settings. Data: {"WEBSITE_RUN_FROM_PACKAGE":"1"}
App Service Application settings are already present.
Package deployment using ZIP Deploy initiated.
Successfully deployed web package to App Service.
NOTE: Run From Package makes wwwroot read-only, so you will receive an error when writing files to this directory.
App Service Application URL: http://xxxxxxxxxxx
Finishing: Azure App Service Deploy: xxxxxxxxxxx
4. web app fails to start, going to diagnose blade -> container issues: Your app timed out
5. going into details we see:
Failing AppCache as unzip from /var/LWASFiles/Sites/xxxxxxxxx/home/site/wwwroot/20210609110706.zip to /mnt/data/docker/images/231072.231072/volumes/xxxxxxxxxxxxx_AppCache_e643595e/_data/appcache was unsuccessful

**Comment by purva-vasudeo** [comment]
Hi @damiand2 ,

Since Run from Package and AppCache are 2 different ways of presenting the app content. These 2 are currently incompatible with each other.

**Comment by damiand2** [comment]
ok, thanks, i had to switch to different task type in azure devops because this one insisted on setting run from package
